/**
 * Short, patient-friendly descriptions for common side effects.
 * Used to explain what each side effect means.
 */
const SIDE_EFFECT_DESCRIPTIONS: Record<string, string> = {
  'Nausea': 'Feeling of sickness or urge to vomit.',
  'Vomiting': 'Forcible emptying of stomach contents.',
  'Headache': 'Pain or discomfort in the head or neck.',
  'Dizziness': 'Sensation of lightheadedness or unsteadiness.',
  'Diarrhoea': 'Loose or watery stools, often more frequent.',
  'Diarrhea': 'Loose or watery stools, often more frequent.',
  'Abdominal pain': 'Pain or discomfort in the stomach or belly area.',
  'Dyspepsia': 'Indigestion or upset stomach.',
  'Rash': 'Redness, bumps or irritation on the skin.',
  'Pruritus': 'Itching of the skin.',
  'Fatigue': 'Tiredness or lack of energy.',
  'Somnolence': 'Drowsiness or sleepiness.',
  'Insomnia': 'Difficulty falling or staying asleep.',
  'Dry mouth': 'Reduced saliva; mouth feels dry.',
  'Constipation': 'Difficulty or infrequency in passing stools.',
  'Hypertension': 'High blood pressure.',
  'Hypotension': 'Low blood pressure.',
  'Oedema': 'Swelling due to fluid buildup in tissues.',
  'Edema': 'Swelling due to fluid buildup in tissues.',
  'Arthralgia': 'Joint pain.',
  'Myalgia': 'Muscle pain or aching.',
  'Back pain': 'Pain in the lower or upper back.',
  'Pyrexia': 'Fever or raised body temperature.',
  'Cough': 'Sudden expulsion of air from the lungs.',
  'Dyspnoea': 'Shortness of breath or difficulty breathing.',
  'Dyspnea': 'Shortness of breath or difficulty breathing.',
  'Pharyngitis': 'Sore throat or inflammation of the pharynx.',
  'Rhinitis': 'Stuffy or runny nose; nasal inflammation.',
  'Urinary tract infection': 'Infection in the bladder or urinary system.',
  'Anaemia': 'Low red blood cell count; may cause tiredness.',
  'Anemia': 'Low red blood cell count; may cause tiredness.',
  'Leukopenia': 'Low white blood cell count.',
  'Thrombocytopenia': 'Low platelet count; may increase bleeding risk.',
  'Hepatotoxicity': 'Liver damage or impaired liver function.',
  'Nephrotoxicity': 'Kidney damage or impaired kidney function.',
  'Tinnitus': 'Ringing or buzzing in the ears.',
  'Hearing loss': 'Reduced ability to hear.',
  'Visual impairment': 'Reduced or blurred vision.',
  'Photosensitivity': 'Increased sensitivity to sunlight; easier sunburn.',
  'Alopecia': 'Hair loss.',
  'Hyperhidrosis': 'Excessive sweating.',
  'Anxiety': 'Worry, nervousness or unease.',
  'Depression': 'Low mood, sadness or loss of interest.',
  'Confusion': 'Difficulty thinking clearly or staying oriented.',
  'Tremor': 'Shaking or trembling of the body.',
  'Seizure': 'Sudden, uncontrolled electrical activity in the brain.',
  'Syncope': 'Fainting or temporary loss of consciousness.',
  'Palpitations': 'Awareness of fast or irregular heartbeat.',
  'Tachycardia': 'Abnormally fast heart rate.',
  'Bradycardia': 'Abnormally slow heart rate.',
  'Chest pain': 'Pain or pressure in the chest area.',
  'Flushing': 'Temporary redness and warmth of the skin.',
  'Hyperglycaemia': 'High blood sugar.',
  'Hyperglycemia': 'High blood sugar.',
  'Hypoglycaemia': 'Low blood sugar.',
  'Hypoglycemia': 'Low blood sugar.',
  'Weight increased': 'Gain in body weight.',
  'Weight decreased': 'Loss of body weight.',
  'Decreased appetite': 'Reduced desire to eat.',
  'Increased appetite': 'Increased desire to eat.',
  'Asthenia': 'Weakness or lack of energy.',
  'Malaise': 'General feeling of being unwell.',
  'Peripheral neuropathy': 'Nerve damage causing numbness or pain in hands/feet.',
  'Gastritis': 'Inflammation of the stomach lining.',
  'Gastrointestinal haemorrhage': 'Bleeding in the digestive tract.',
  'Gastrointestinal hemorrhage': 'Bleeding in the digestive tract.',
  'Pancreatitis': 'Inflammation of the pancreas.',
  'Stevens-Johnson syndrome': 'Serious skin and mucous membrane reaction.',
  'Toxic epidermal necrolysis': 'Severe skin reaction with blistering.',
  'Anaphylaxis': 'Severe, life-threatening allergic reaction.',
  'Angioedema': 'Swelling under the skin, often face or throat.',
  'Drug hypersensitivity': 'Allergic or hypersensitive reaction to the drug.',
  'Agranulocytosis': 'Severe drop in white blood cells (neutrophils).',
  'Aplastic anaemia': 'Bone marrow failure; low blood cells.',
  'Aplastic anemia': 'Bone marrow failure; low blood cells.',
  'Rhabdomyolysis': 'Breakdown of muscle tissue; can affect kidneys.',
  'Serotonin syndrome': 'Dangerous excess of serotonin (e.g. with some antidepressants).',
  'Suicidal ideation': 'Thoughts of harming or killing oneself.',
  'Hallucination': 'Seeing or hearing things that are not there.',
  'Psychotic disorder': 'Loss of contact with reality.',
  'Withdrawal syndrome': 'Symptoms when stopping the medicine suddenly.',
  'Drug dependence': 'Physical or psychological reliance on the drug.',
  'Abdominal cramps': 'Cramping or tightening pain in the belly.',
  'Gastrointestinal pain': 'Pain in the stomach or intestines.',
  'Flatulence': 'Gas in the digestive tract; bloating.',
  'Dysphagia': 'Difficulty swallowing.',
  'Stomatitis': 'Mouth sores or inflammation.',
  'Gingival bleeding': 'Bleeding gums.',
  'Epistaxis': 'Nosebleed.',
  'Bruising': 'Easy or unexplained bruising.',
  'Petechiae': 'Small red or purple spots on the skin.',
  'Urticaria': 'Hives; itchy, raised welts on the skin.',
  'Erythema': 'Redness of the skin.',
  'Dermatitis': 'Skin inflammation or rash.',
  'Hyperkalaemia': 'High potassium level in the blood.',
  'Hyperkalemia': 'High potassium level in the blood.',
  'Hypokalaemia': 'Low potassium level in the blood.',
  'Hypokalemia': 'Low potassium level in the blood.',
  'Hyponatraemia': 'Low sodium level in the blood.',
  'Hyponatremia': 'Low sodium level in the blood.',
  'Hypomagnesaemia': 'Low magnesium level in the blood.',
  'Hypomagnesemia': 'Low magnesium level in the blood.',
};

/**
 * Returns a short description for a side effect name.
 * Uses exact match first, then case-insensitive, then fallback.
 */
export function getSideEffectDescription(sideEffectName: string): string {
  const trimmed = sideEffectName.trim();
  if (SIDE_EFFECT_DESCRIPTIONS[trimmed]) {
    return SIDE_EFFECT_DESCRIPTIONS[trimmed];
  }
  const lower = trimmed.toLowerCase();
  const entry = Object.entries(SIDE_EFFECT_DESCRIPTIONS).find(
    ([key]) => key.toLowerCase() === lower
  );
  if (entry) return entry[1];
  return 'A potential effect of this medicine. Discuss with your doctor or pharmacist if you are concerned.';
}
